# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu8.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(1125, 862)
        self.gridLayout_4 = QtGui.QGridLayout(Dialog)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.MainImage = QtGui.QLabel(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(6)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MainImage.sizePolicy().hasHeightForWidth())
        self.MainImage.setSizePolicy(sizePolicy)
        self.MainImage.setStyleSheet(_fromUtf8("background-color: rgb(47, 47, 47);"))
        self.MainImage.setText(_fromUtf8(""))
        self.MainImage.setObjectName(_fromUtf8("MainImage"))
        self.gridLayout_4.addWidget(self.MainImage, 0, 0, 1, 1)
        self.scrollArea = QtGui.QScrollArea(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(350, 0))
        self.scrollArea.setBaseSize(QtCore.QSize(100, 0))
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 385, 847))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_2 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_6 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setText(_fromUtf8(""))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout.addWidget(self.label_6)
        self.CollectImage = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CollectImage.sizePolicy().hasHeightForWidth())
        self.CollectImage.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.CollectImage.setFont(font)
        self.CollectImage.setStyleSheet(_fromUtf8(""))
        self.CollectImage.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.CollectImage.setObjectName(_fromUtf8("CollectImage"))
        self.verticalLayout.addWidget(self.CollectImage)
        self.frame_4 = QtGui.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.gridLayout = QtGui.QGridLayout(self.frame_4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.ShowWideView = QtGui.QRadioButton(self.frame_4)
        self.ShowWideView.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ShowWideView.setChecked(True)
        self.ShowWideView.setObjectName(_fromUtf8("ShowWideView"))
        self.verticalLayout_5.addWidget(self.ShowWideView)
        self.ShowLStereo = QtGui.QRadioButton(self.frame_4)
        self.ShowLStereo.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ShowLStereo.setObjectName(_fromUtf8("ShowLStereo"))
        self.verticalLayout_5.addWidget(self.ShowLStereo)
        self.ShowRStereo = QtGui.QRadioButton(self.frame_4)
        self.ShowRStereo.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ShowRStereo.setObjectName(_fromUtf8("ShowRStereo"))
        self.verticalLayout_5.addWidget(self.ShowRStereo)
        self.verticalLayout_2.addLayout(self.verticalLayout_5)
        self.SaveVideo = QtGui.QCheckBox(self.frame_4)
        self.SaveVideo.setFocusPolicy(QtCore.Qt.NoFocus)
        self.SaveVideo.setObjectName(_fromUtf8("SaveVideo"))
        self.verticalLayout_2.addWidget(self.SaveVideo)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.line = QtGui.QFrame(self.frame_4)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout.addWidget(self.line)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.TakeCalibImages = QtGui.QPushButton(self.frame_4)
        self.TakeCalibImages.setFocusPolicy(QtCore.Qt.NoFocus)
        self.TakeCalibImages.setObjectName(_fromUtf8("TakeCalibImages"))
        self.verticalLayout_6.addWidget(self.TakeCalibImages)
        self.line_2 = QtGui.QFrame(self.frame_4)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_6.addWidget(self.line_2)
        self.TakeImageSet = QtGui.QPushButton(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TakeImageSet.sizePolicy().hasHeightForWidth())
        self.TakeImageSet.setSizePolicy(sizePolicy)
        self.TakeImageSet.setFocusPolicy(QtCore.Qt.NoFocus)
        self.TakeImageSet.setObjectName(_fromUtf8("TakeImageSet"))
        self.verticalLayout_6.addWidget(self.TakeImageSet)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_4)
        self.ManualControl = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ManualControl.sizePolicy().hasHeightForWidth())
        self.ManualControl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ManualControl.setFont(font)
        self.ManualControl.setObjectName(_fromUtf8("ManualControl"))
        self.verticalLayout.addWidget(self.ManualControl)
        self.frame_6 = QtGui.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame_6)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.verticalLayout_21 = QtGui.QVBoxLayout()
        self.verticalLayout_21.setObjectName(_fromUtf8("verticalLayout_21"))
        self.horizontalLayout_31 = QtGui.QHBoxLayout()
        self.horizontalLayout_31.setObjectName(_fromUtf8("horizontalLayout_31"))
        self.StatusLabel_5 = QtGui.QLabel(self.frame_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StatusLabel_5.sizePolicy().hasHeightForWidth())
        self.StatusLabel_5.setSizePolicy(sizePolicy)
        self.StatusLabel_5.setStyleSheet(_fromUtf8(""))
        self.StatusLabel_5.setObjectName(_fromUtf8("StatusLabel_5"))
        self.horizontalLayout_31.addWidget(self.StatusLabel_5)
        self.verticalLayout_21.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.verticalLayout_27 = QtGui.QVBoxLayout()
        self.verticalLayout_27.setSpacing(0)
        self.verticalLayout_27.setObjectName(_fromUtf8("verticalLayout_27"))
        self.horizontalLayout_32 = QtGui.QHBoxLayout()
        self.horizontalLayout_32.setObjectName(_fromUtf8("horizontalLayout_32"))
        self.label_25 = QtGui.QLabel(self.frame_6)
        self.label_25.setText(_fromUtf8(""))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.horizontalLayout_32.addWidget(self.label_25)
        self.label_31 = QtGui.QLabel(self.frame_6)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.horizontalLayout_32.addWidget(self.label_31)
        self.label_44 = QtGui.QLabel(self.frame_6)
        self.label_44.setText(_fromUtf8(""))
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.horizontalLayout_32.addWidget(self.label_44)
        self.verticalLayout_27.addLayout(self.horizontalLayout_32)
        self.horizontalLayout_33 = QtGui.QHBoxLayout()
        self.horizontalLayout_33.setObjectName(_fromUtf8("horizontalLayout_33"))
        self.label_45 = QtGui.QLabel(self.frame_6)
        self.label_45.setText(_fromUtf8(""))
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.horizontalLayout_33.addWidget(self.label_45)
        self.ViewLabel = QtGui.QLabel(self.frame_6)
        self.ViewLabel.setStyleSheet(_fromUtf8("font: 63 11pt \"Ubuntu\";"))
        self.ViewLabel.setObjectName(_fromUtf8("ViewLabel"))
        self.horizontalLayout_33.addWidget(self.ViewLabel)
        self.label_46 = QtGui.QLabel(self.frame_6)
        self.label_46.setText(_fromUtf8(""))
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.horizontalLayout_33.addWidget(self.label_46)
        self.verticalLayout_27.addLayout(self.horizontalLayout_33)
        self.horizontalLayout_11.addLayout(self.verticalLayout_27)
        self.verticalLayout_28 = QtGui.QVBoxLayout()
        self.verticalLayout_28.setSpacing(0)
        self.verticalLayout_28.setObjectName(_fromUtf8("verticalLayout_28"))
        self.horizontalLayout_34 = QtGui.QHBoxLayout()
        self.horizontalLayout_34.setObjectName(_fromUtf8("horizontalLayout_34"))
        self.label_17 = QtGui.QLabel(self.frame_6)
        self.label_17.setText(_fromUtf8(""))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_34.addWidget(self.label_17)
        self.label_19 = QtGui.QLabel(self.frame_6)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_34.addWidget(self.label_19)
        self.label_20 = QtGui.QLabel(self.frame_6)
        self.label_20.setText(_fromUtf8(""))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_34.addWidget(self.label_20)
        self.verticalLayout_28.addLayout(self.horizontalLayout_34)
        self.horizontalLayout_35 = QtGui.QHBoxLayout()
        self.horizontalLayout_35.setObjectName(_fromUtf8("horizontalLayout_35"))
        self.label_47 = QtGui.QLabel(self.frame_6)
        self.label_47.setText(_fromUtf8(""))
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.horizontalLayout_35.addWidget(self.label_47)
        self.AzLabel = QtGui.QLabel(self.frame_6)
        self.AzLabel.setStyleSheet(_fromUtf8("font: 63 11pt \"Ubuntu\";"))
        self.AzLabel.setText(_fromUtf8(""))
        self.AzLabel.setObjectName(_fromUtf8("AzLabel"))
        self.horizontalLayout_35.addWidget(self.AzLabel)
        self.label_48 = QtGui.QLabel(self.frame_6)
        self.label_48.setText(_fromUtf8(""))
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.horizontalLayout_35.addWidget(self.label_48)
        self.verticalLayout_28.addLayout(self.horizontalLayout_35)
        self.horizontalLayout_11.addLayout(self.verticalLayout_28)
        self.verticalLayout_29 = QtGui.QVBoxLayout()
        self.verticalLayout_29.setSpacing(0)
        self.verticalLayout_29.setObjectName(_fromUtf8("verticalLayout_29"))
        self.horizontalLayout_36 = QtGui.QHBoxLayout()
        self.horizontalLayout_36.setObjectName(_fromUtf8("horizontalLayout_36"))
        self.label_49 = QtGui.QLabel(self.frame_6)
        self.label_49.setText(_fromUtf8(""))
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.horizontalLayout_36.addWidget(self.label_49)
        self.label_50 = QtGui.QLabel(self.frame_6)
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.horizontalLayout_36.addWidget(self.label_50)
        self.label_51 = QtGui.QLabel(self.frame_6)
        self.label_51.setText(_fromUtf8(""))
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.horizontalLayout_36.addWidget(self.label_51)
        self.verticalLayout_29.addLayout(self.horizontalLayout_36)
        self.horizontalLayout_37 = QtGui.QHBoxLayout()
        self.horizontalLayout_37.setObjectName(_fromUtf8("horizontalLayout_37"))
        self.label_52 = QtGui.QLabel(self.frame_6)
        self.label_52.setText(_fromUtf8(""))
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.horizontalLayout_37.addWidget(self.label_52)
        self.ZenLabel = QtGui.QLabel(self.frame_6)
        self.ZenLabel.setStyleSheet(_fromUtf8("font: 63 11pt \"Ubuntu\";"))
        self.ZenLabel.setText(_fromUtf8(""))
        self.ZenLabel.setObjectName(_fromUtf8("ZenLabel"))
        self.horizontalLayout_37.addWidget(self.ZenLabel)
        self.label_53 = QtGui.QLabel(self.frame_6)
        self.label_53.setText(_fromUtf8(""))
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.horizontalLayout_37.addWidget(self.label_53)
        self.verticalLayout_29.addLayout(self.horizontalLayout_37)
        self.horizontalLayout_11.addLayout(self.verticalLayout_29)
        self.verticalLayout_21.addLayout(self.horizontalLayout_11)
        self.verticalLayout_10.addLayout(self.verticalLayout_21)
        self.label_54 = QtGui.QLabel(self.frame_6)
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.verticalLayout_10.addWidget(self.label_54, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_38 = QtGui.QHBoxLayout()
        self.horizontalLayout_38.setObjectName(_fromUtf8("horizontalLayout_38"))
        self.StatusLabel = QtGui.QLabel(self.frame_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StatusLabel.sizePolicy().hasHeightForWidth())
        self.StatusLabel.setSizePolicy(sizePolicy)
        self.StatusLabel.setStyleSheet(_fromUtf8("font: 63 11pt \"Ubuntu\";"))
        self.StatusLabel.setObjectName(_fromUtf8("StatusLabel"))
        self.horizontalLayout_38.addWidget(self.StatusLabel)
        self.verticalLayout_10.addLayout(self.horizontalLayout_38)
        self.line_5 = QtGui.QFrame(self.frame_6)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.verticalLayout_10.addWidget(self.line_5)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_5 = QtGui.QLabel(self.frame_6)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_7.addWidget(self.label_5)
        self.TimeInput = QtGui.QLineEdit(self.frame_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TimeInput.sizePolicy().hasHeightForWidth())
        self.TimeInput.setSizePolicy(sizePolicy)
        self.TimeInput.setObjectName(_fromUtf8("TimeInput"))
        self.horizontalLayout_7.addWidget(self.TimeInput)
        self.horizontalLayout_7.setStretch(0, 4)
        self.horizontalLayout_7.setStretch(1, 1)
        self.verticalLayout_11.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_39 = QtGui.QHBoxLayout()
        self.horizontalLayout_39.setObjectName(_fromUtf8("horizontalLayout_39"))
        self.label_12 = QtGui.QLabel(self.frame_6)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_39.addWidget(self.label_12)
        self.AzInput = QtGui.QLineEdit(self.frame_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AzInput.sizePolicy().hasHeightForWidth())
        self.AzInput.setSizePolicy(sizePolicy)
        self.AzInput.setReadOnly(False)
        self.AzInput.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.AzInput.setObjectName(_fromUtf8("AzInput"))
        self.horizontalLayout_39.addWidget(self.AzInput)
        self.verticalLayout_11.addLayout(self.horizontalLayout_39)
        self.horizontalLayout_40 = QtGui.QHBoxLayout()
        self.horizontalLayout_40.setObjectName(_fromUtf8("horizontalLayout_40"))
        self.label_55 = QtGui.QLabel(self.frame_6)
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.horizontalLayout_40.addWidget(self.label_55)
        self.ZenInput = QtGui.QLineEdit(self.frame_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ZenInput.sizePolicy().hasHeightForWidth())
        self.ZenInput.setSizePolicy(sizePolicy)
        self.ZenInput.setObjectName(_fromUtf8("ZenInput"))
        self.horizontalLayout_40.addWidget(self.ZenInput)
        self.verticalLayout_11.addLayout(self.horizontalLayout_40)
        self.verticalLayout_10.addLayout(self.verticalLayout_11)
        self.horizontalLayout_41 = QtGui.QHBoxLayout()
        self.horizontalLayout_41.setObjectName(_fromUtf8("horizontalLayout_41"))
        self.Run = QtGui.QPushButton(self.frame_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Run.sizePolicy().hasHeightForWidth())
        self.Run.setSizePolicy(sizePolicy)
        self.Run.setMinimumSize(QtCore.QSize(100, 50))
        self.Run.setBaseSize(QtCore.QSize(100, 75))
        self.Run.setObjectName(_fromUtf8("Run"))
        self.horizontalLayout_41.addWidget(self.Run)
        self.Stop = QtGui.QPushButton(self.frame_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Stop.sizePolicy().hasHeightForWidth())
        self.Stop.setSizePolicy(sizePolicy)
        self.Stop.setMinimumSize(QtCore.QSize(100, 50))
        self.Stop.setBaseSize(QtCore.QSize(100, 75))
        self.Stop.setObjectName(_fromUtf8("Stop"))
        self.horizontalLayout_41.addWidget(self.Stop)
        self.verticalLayout_10.addLayout(self.horizontalLayout_41)
        self.verticalLayout_3.addLayout(self.verticalLayout_10)
        self.verticalLayout.addWidget(self.frame_6)
        self.ManualControl_2 = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ManualControl_2.sizePolicy().hasHeightForWidth())
        self.ManualControl_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ManualControl_2.setFont(font)
        self.ManualControl_2.setObjectName(_fromUtf8("ManualControl_2"))
        self.verticalLayout.addWidget(self.ManualControl_2)
        self.frame = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_5 = QtGui.QGridLayout(self.frame)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.horizontalLayout_44 = QtGui.QHBoxLayout()
        self.horizontalLayout_44.setObjectName(_fromUtf8("horizontalLayout_44"))
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.horizontalLayout_45 = QtGui.QHBoxLayout()
        self.horizontalLayout_45.setObjectName(_fromUtf8("horizontalLayout_45"))
        self.label_9 = QtGui.QLabel(self.frame)
        self.label_9.setStyleSheet(_fromUtf8("font: 63 8pt \"Ubuntu\";"))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_45.addWidget(self.label_9)
        self.CurrentStep_4 = QtGui.QLabel(self.frame)
        self.CurrentStep_4.setStyleSheet(_fromUtf8("font: 63 9pt \"Ubuntu\";"))
        self.CurrentStep_4.setObjectName(_fromUtf8("CurrentStep_4"))
        self.horizontalLayout_45.addWidget(self.CurrentStep_4)
        self.verticalLayout_14.addLayout(self.horizontalLayout_45)
        self.StepSmall = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StepSmall.sizePolicy().hasHeightForWidth())
        self.StepSmall.setSizePolicy(sizePolicy)
        self.StepSmall.setMaximumSize(QtCore.QSize(100, 16777215))
        self.StepSmall.setObjectName(_fromUtf8("StepSmall"))
        self.verticalLayout_14.addWidget(self.StepSmall)
        self.StepMedium = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StepMedium.sizePolicy().hasHeightForWidth())
        self.StepMedium.setSizePolicy(sizePolicy)
        self.StepMedium.setMaximumSize(QtCore.QSize(100, 16777215))
        self.StepMedium.setObjectName(_fromUtf8("StepMedium"))
        self.verticalLayout_14.addWidget(self.StepMedium)
        self.StepLarge = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StepLarge.sizePolicy().hasHeightForWidth())
        self.StepLarge.setSizePolicy(sizePolicy)
        self.StepLarge.setMaximumSize(QtCore.QSize(100, 16777215))
        self.StepLarge.setObjectName(_fromUtf8("StepLarge"))
        self.verticalLayout_14.addWidget(self.StepLarge)
        self.horizontalLayout_44.addLayout(self.verticalLayout_14)
        self.verticalLayout_31 = QtGui.QVBoxLayout()
        self.verticalLayout_31.setObjectName(_fromUtf8("verticalLayout_31"))
        self.MoveRight = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MoveRight.sizePolicy().hasHeightForWidth())
        self.MoveRight.setSizePolicy(sizePolicy)
        self.MoveRight.setMaximumSize(QtCore.QSize(100, 16777215))
        self.MoveRight.setObjectName(_fromUtf8("MoveRight"))
        self.verticalLayout_31.addWidget(self.MoveRight)
        self.MoveLeft = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MoveLeft.sizePolicy().hasHeightForWidth())
        self.MoveLeft.setSizePolicy(sizePolicy)
        self.MoveLeft.setMaximumSize(QtCore.QSize(100, 16777215))
        self.MoveLeft.setObjectName(_fromUtf8("MoveLeft"))
        self.verticalLayout_31.addWidget(self.MoveLeft)
        self.MoveUp = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MoveUp.sizePolicy().hasHeightForWidth())
        self.MoveUp.setSizePolicy(sizePolicy)
        self.MoveUp.setMaximumSize(QtCore.QSize(100, 16777215))
        self.MoveUp.setObjectName(_fromUtf8("MoveUp"))
        self.verticalLayout_31.addWidget(self.MoveUp)
        self.MoveDown = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MoveDown.sizePolicy().hasHeightForWidth())
        self.MoveDown.setSizePolicy(sizePolicy)
        self.MoveDown.setMaximumSize(QtCore.QSize(100, 16777215))
        self.MoveDown.setObjectName(_fromUtf8("MoveDown"))
        self.verticalLayout_31.addWidget(self.MoveDown)
        self.horizontalLayout_44.addLayout(self.verticalLayout_31)
        self.gridLayout_5.addLayout(self.horizontalLayout_44, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame)
        self.ProcessData = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ProcessData.sizePolicy().hasHeightForWidth())
        self.ProcessData.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ProcessData.setFont(font)
        self.ProcessData.setObjectName(_fromUtf8("ProcessData"))
        self.verticalLayout.addWidget(self.ProcessData)
        self.frame_5 = QtGui.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.gridLayout_3 = QtGui.QGridLayout(self.frame_5)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.verticalLayout_18 = QtGui.QVBoxLayout()
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.verticalLayout_19 = QtGui.QVBoxLayout()
        self.verticalLayout_19.setObjectName(_fromUtf8("verticalLayout_19"))
        self.Calibrate_2 = QtGui.QPushButton(self.frame_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Calibrate_2.sizePolicy().hasHeightForWidth())
        self.Calibrate_2.setSizePolicy(sizePolicy)
        self.Calibrate_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.Calibrate_2.setObjectName(_fromUtf8("Calibrate_2"))
        self.verticalLayout_19.addWidget(self.Calibrate_2)
        self.pushButton_15 = QtGui.QPushButton(self.frame_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_15.sizePolicy().hasHeightForWidth())
        self.pushButton_15.setSizePolicy(sizePolicy)
        self.pushButton_15.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_15.setObjectName(_fromUtf8("pushButton_15"))
        self.verticalLayout_19.addWidget(self.pushButton_15)
        self.horizontalLayout_9.addLayout(self.verticalLayout_19)
        self.verticalLayout_20 = QtGui.QVBoxLayout()
        self.verticalLayout_20.setObjectName(_fromUtf8("verticalLayout_20"))
        self.pushButton_16 = QtGui.QPushButton(self.frame_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_16.sizePolicy().hasHeightForWidth())
        self.pushButton_16.setSizePolicy(sizePolicy)
        self.pushButton_16.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_16.setObjectName(_fromUtf8("pushButton_16"))
        self.verticalLayout_20.addWidget(self.pushButton_16)
        self.pushButton_17 = QtGui.QPushButton(self.frame_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_17.sizePolicy().hasHeightForWidth())
        self.pushButton_17.setSizePolicy(sizePolicy)
        self.pushButton_17.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_17.setObjectName(_fromUtf8("pushButton_17"))
        self.verticalLayout_20.addWidget(self.pushButton_17)
        self.horizontalLayout_9.addLayout(self.verticalLayout_20)
        self.verticalLayout_18.addLayout(self.horizontalLayout_9)
        self.gridLayout_3.addLayout(self.verticalLayout_18, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_5)
        self.label_2 = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 5))
        self.label_2.setText(_fromUtf8(""))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_4.addWidget(self.scrollArea, 0, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.MainImage.setToolTip(_translate("Dialog", "Time between each view.", None))
        self.CollectImage.setText(_translate("Dialog", "Camera Control", None))
        self.ShowWideView.setText(_translate("Dialog", "Show Wide View", None))
        self.ShowLStereo.setText(_translate("Dialog", "Show L Stereo", None))
        self.ShowRStereo.setText(_translate("Dialog", "Show R Stereo", None))
        self.SaveVideo.setText(_translate("Dialog", "Save Video", None))
        self.TakeCalibImages.setText(_translate("Dialog", "Take Calib. Images", None))
        self.TakeImageSet.setText(_translate("Dialog", "Take Image Set", None))
        self.ManualControl.setText(_translate("Dialog", "Pan Tilt Automatic Control", None))
        self.StatusLabel_5.setText(_translate("Dialog", "Current Conditions:", None))
        self.label_31.setText(_translate("Dialog", "Viewing Case", None))
        self.ViewLabel.setText(_translate("Dialog", "0", None))
        self.label_19.setText(_translate("Dialog", "Pan Angle", None))
        self.label_50.setText(_translate("Dialog", "Tilt Angle", None))
        self.label_54.setText(_translate("Dialog", "Status:", None))
        self.StatusLabel.setText(_translate("Dialog", "Idle", None))
        self.label_5.setText(_translate("Dialog", "Sleep Time (sec):          ", None))
        self.TimeInput.setText(_translate("Dialog", "1", None))
        self.label_12.setText(_translate("Dialog", "Pan Angle(s) (deg):  ", None))
        self.AzInput.setText(_translate("Dialog", "10,70,130", None))
        self.AzInput.setPlaceholderText(_translate("Dialog", "angle1,angle2...", None))
        self.label_55.setText(_translate("Dialog", "Tilt Angle(s) (deg):", None))
        self.ZenInput.setText(_translate("Dialog", "40,100", None))
        self.ZenInput.setPlaceholderText(_translate("Dialog", "angle1,angle2...", None))
        self.Run.setText(_translate("Dialog", "Run", None))
        self.Stop.setText(_translate("Dialog", "Stop", None))
        self.ManualControl_2.setText(_translate("Dialog", "Pan Tilt Manual Control", None))
        self.label_9.setText(_translate("Dialog", "Current Step:", None))
        self.CurrentStep_4.setText(_translate("Dialog", "60", None))
        self.StepSmall.setText(_translate("Dialog", "Step 30", None))
        self.StepMedium.setText(_translate("Dialog", "Step 60", None))
        self.StepLarge.setText(_translate("Dialog", "Step 120", None))
        self.MoveRight.setText(_translate("Dialog", "Move Right", None))
        self.MoveLeft.setText(_translate("Dialog", "Move Left", None))
        self.MoveUp.setText(_translate("Dialog", "Move Up", None))
        self.MoveDown.setText(_translate("Dialog", "Move Down", None))
        self.ProcessData.setText(_translate("Dialog", "Process Data", None))
        self.Calibrate_2.setText(_translate("Dialog", "...", None))
        self.pushButton_15.setText(_translate("Dialog", "...", None))
        self.pushButton_16.setText(_translate("Dialog", "...", None))
        self.pushButton_17.setText(_translate("Dialog", "...", None))
